apiVersion: extauth.solo.io/v1
kind: AuthConfig
metadata:
  name: apikey-auth
  namespace: httpbin
spec:
  configs:
  - apiKeyAuth:
      # Optional; defaults to api-key.
      headerName: api-key
      labelSelector:
        extauth: apikey
